substitutions:
  friendly_name: Dovecot 1 Bedroom
  name: "devola-heater"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  friendly_name: "${friendly_name} Heater"
  project:
    name: "jon.devola"
    version: "1.0.0"

dashboard_import:
  package_import_url: github://esphome-devola/devola-heater.yaml
  import_full_config: True
esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heater Fallback Hotspot"
    password: "3giZYZIHEHeS"

captive_portal:
tuya:

uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600
  id: mcu_uart

climate:
  - platform: tuya
    name: "Dovecot 1 Bedroom Heater"
    switch_datapoint: 1
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    supports_heat: true
    supports_cool: false
    visual: 
      temperature_step: 1
      max_temperature: 45
      min_temperature: 5
select:
  - platform: "tuya"
    name: "High/Low Power Mode"
    enum_datapoint: 5
    optimistic: true
    options:
      0: Low
      1: High
