substitutions:
  friendly_name: "devola-heater"
  name: "devola-heater"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  friendly_name: "${friendly_name}"
  project:
    name: "jon.devola"
    version: "1.0.0"

# dashboard_import:
#   package_import_url: github://cloverleyhall/esphome-devola/devola-heater.yaml@main
#   import_full_config: false
esp8266:
  board: esp01_1m

# Enable logging
logger:
ota:
  platform: esphome
# Enable Home Assistant API
api:
wifi:
  ap:
    ssid: "Heater Fallback Hotspot"
    password: "3giZYZIHEHeS"

captive_portal:
tuya:

uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600
  id: mcu_uart

climate:
  - platform: tuya
    name: "${friendly_name}"
    switch_datapoint: 1
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    supports_heat: true
    supports_cool: false
    visual: 
      temperature_step: 1
      max_temperature: 45
      min_temperature: 5
select:
  - platform: "tuya"
    name: "High/Low Power Mode"
    enum_datapoint: 5
    optimistic: true
    options:
      0: Low
      1: High
